### ISSUE TITLE
Bug? Slate, Marble and Limestone cannot be used to craft tools.

### ISSUE THREAD

**Issue by K0-RR** [HexBugOrion/UnEarthed#13]
I don't know if this is by design or not.

**Comment by bessiq** [comment]
I thought this might be a bug also, but I think any UE stone that gives cobble when you break it follows vanilla logic - e.g. you can make stone tools with vanilla _cobblestone_ but not vanilla stone. I tested with UE slate cobblestone and was able to craft stone tools with it. UE is using the vanilla tags: `minecraft:stone_crafting_materials` and `minecraft:stone_tool_materials`.

However, I found a related issue if Quark is present. Quark adds its own tag - `quark:stone_tool_materials` - which in itself doesn't break anything, but adds more stone types mainly by including `forge:stone`. But what Quark also does is overwrite the vanilla stone tool recipes, which breaks tool crafting with any UE stone due to 1) it not being tagged as `forge:stone`, and 2) Quark using an apparently older version of the vanilla recipes:

**Vanilla stone axe recipe** (updated at some point in 1.16 to include blackstone presumably):
```
{
  "type": "minecraft:crafting_shaped",
  "pattern": [
    "XX",
    "X#",
    " #"
  ],
  "key": {
    "#": {
      "item": "minecraft:stick"
    },
    "X": {
      "tag": "minecraft:stone_tool_materials"
    }
  },
  "result": {
    "item": "minecraft:stone_axe"
  }
}
```

**Quark stone axe recipe:**
```
{
  "type": "minecraft:crafting_shaped",
  "pattern": [
    "XX",
    "X#",
    " #"
  ],
  "key": {
    "#": {
      "item": "minecraft:stick"
    },
    "X": {
      "item": "minecraft:cobblestone"
    }
  },
  "result": {
    "item": "minecraft:stone_axe"
  },
  "conditions": [
    {
      "type": "forge:not",
      "value": {
        "type": "quark:flag",
        "flag": "better_stone_tools"
      }
    }
  ]
}
```

In theory, if you disabled "Better Stone Tool Crafting" in the Quark config, it would revert the recipes to the default vanilla versions based on the included condition. But instead of using the default recipe ingredient - `"tag": "minecraft:stone_tool_materials"` - Quark uses `minecraft:cobblestone`.

Ideally, an issue could be opened with Quark to update their stone crafting recipes to mirror the newer vanilla ones. Alternatives/workarounds would be:
- adding tags to UE stone such as `forge:stone` or `quark:stone_tool_materials` (I did this just because I couldn't find a good reason not to - seems like an oversight?)
- overwriting Quark's stone crafting recipes with a datapack

Anyway, all the Quark stuff really isn't applicable to the original issue, but it just came up when I was testing and couldn't get _any_ UE stone to craft a tool, then realized it was due to Quark.

**Comment by CorgiTaco** [comment]
Should be fixed in latest
